server:
  port: 8081

spring:
  application:
    name: account # ? ???? ??? ??? ?????.

  datasource:
    url: jdbc:mysql://localhost:3306/account?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root        # ?? ???? ??
    password: 1234        # ?? ????? ??
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        # Hibernate 6.x? dialect ?????. ???? ??? ?? ? ??:
        # dialect: org.hibernate.dialect.MySQLDialect        # ??(??)
        # dialect: org.hibernate.dialect.MySQL8Dialect       # MySQL 8 ?? ??

jwt:
  secret:
    key: petlendar_password_key_by_seob_1234567890



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}