server:
  port: 8081


spring:
  application:
    name: account # 이 서비스의 고유한 이름을 명시합니다.
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        # Hibernate 6.x? dialect ?????. ???? ??? ?? ? ??:
        # dialect: org.hibernate.dialect.MySQLDialect        # ??(??)
        # dialect: org.hibernate.dialect.MySQL8Dialect       # MySQL 8 ?? ??

token:
  secret:
    key: SpringBootJWTHeplerTokenSecretKeyValue123!@#


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql: TRACE