server:
  port: 0

spring:
  application:
    name: user-service  # 이 서비스의 고유한 이름을 명시합니다.

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul  # `user`는 DB 이름입니다.
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update



eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}
    metadata-map:
      management.port: ${management.server.port:0}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 0


token:
  secret:
    key: SpringBootJWTHeplerTokenSecretKeyValue123!@#
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12
