server:
  port: 0

spring:
  application:
    name: store # ?? ? ??? service?? ??? ??
  datasource:
    url: jdbc:mysql://localhost:3306/store
      ?serverTimezone=Asia/Seoul
      &characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}
    metadata-map:
      management.port: ${management.server.port:0}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 0

publicdata:
  api:
    base-url: api.odcloud.kr/api
    key: ${PUBLICDATA_SERVICE_KEY}

logging:
  level:
    root: DEBUG
    com.example: DEBUG