server:
  port: 0

spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false



eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}
    metadata-map:
      management.port: ${management.server.port:0}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 0

publicData:
  api:
    base-url: "https://api.odcloud.kr/api/nts-businessman/v1"
    service-key: ${PUBLIC_DATA_SERVICE_KEY}

logging:
  level:
    root: INFO
    com.example: INFO


openapi:
  service:
    url: http://localhost:8080/store



