server:
  port: 0

spring:
  application:
    name: item  # ?? ? ??? service?? ??? ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/item
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${spring.application.name}-group

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}
    metadata-map:
      management.port: ${management.server.port:0}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 0

logging:
  level:
    root: INFO
    com.example: INFO

springdoc:
  api-docs:
    path: /item/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

openapi:
  service:
    # 예: user 모듈
    url: http://localhost:8080/item
    # 운영: https://api.example.com/user-service

