server:
  port: 0

spring:
  application:
    name: image  # ?? ? ??? service?? ??? ??

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}
    metadata-map:
      management.port: ${management.server.port:0}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 0



openapi:
  service:
    # 예: user 모듈
    url: http://localhost:8080/image
    # 운영: https://api.example.com/user-service