server:
  port: 0

spring:
  application:
    name: image
  datasource:
    url: jdbc:mysql://localhost:3306/image
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}-group


  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}
    metadata-map:
      management.port: ${management.server.port:0}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 0

openapi:
  service:
    # 예: user 모듈
    url: http://localhost:8080/image
    # 운영: https://api.example.com/user-service

file:
  upload-dir: /Users/mirae/Sweet-Deal/image/src/resources/static/uploads/
  # 실제 저장 폴더
  public-path: /image/upload/
  public-base-url: http://localhost:8080
